export const content = {
  en: {
    navLinks: ['Pitch', 'Skills', 'Experience', 'Projects', 'Open data', 'Contact'],
    heroTag: 'Data Analyst · Data Engineer · Full Stack Developer',
    heroDesc: 'Transforming complex data into decisions that drive real impact. Specialized in health analytics, ETL pipelines, and full stack development for operations and clinical environments.',
    cta1: 'Get in Touch', cta2: 'View Projects',
    statsLabels: ['Years Experience', 'Time Saved', 'Asset Loss Reduced', 'DDD Reduction', 'Languages'],
    pitchTag: '// 00 — Why Hire Me', pitchTitle: 'The Pitch',
    pitchHeadline: 'You have data.\nYou need decisions.',
    pitchDesc: "Most businesses sit on raw data that nobody's turning into insight. I close that gap — building pipelines that clean and centralize your data, dashboards your team will actually use, and automations that cut manual work entirely. I've done it inside hospital systems and health operations. I can do it for you.",
    pitchCards: [
      { icon: '⚙', title: 'Data Engineer', desc: 'ETL pipelines, PostgreSQL, Power Automate. Your data, clean and centralized.' },
      { icon: '📊', title: 'Data Analyst', desc: 'Power BI, Tableau, R, Python. Insights your executives can act on.' },
      { icon: '🌐', title: 'Full Stack Dev', desc: 'React, TypeScript, SQL. Custom modules built around your workflow.' },
    ],
    s1tag: '// 01 — Capabilities', s1title: 'Technical Stack',
    s2tag: '// 02 — Track Record', s2title: 'Experience',
    s3tag: '// 03 — Built Things', s3title: 'Projects',
    vizTag: '// Live — Portfolio viz',
    vizTitle: 'Top 10 products by average price',
    vizCaption:
      'Bar chart from public JSON (Datos Abiertos Colombia · canasta familiar pipeline). Axes: Producto vs precio_promedio in COP.',
    vizMetaLeft: 'Sorted by precio_promedio · descending',
    vizMetaRight: 'Recharts · ResponsiveContainer',
    s4tag: '// 04 — Contact', s4title: "Let's Talk",
    avail: 'Available for freelance projects',
    contactDesc: "Need a data analyst, engineer, or developer who understands the business side too? Let's build something that actually moves the needle.",
    contactTabChannels: 'Direct',
    contactTabForm: 'Contact Form',
    formName: 'Name',
    formEmail: 'Email',
    formMessage: 'Message',
    formSubmit: 'Send message',
    formSending: 'Sending...',
    formSuccess: "Thanks - I'll get back to you soon.",
    formError: 'Could not send. Please try again or use the email link.',
    formHintNoKey: 'Add VITE_WEB3FORMS_ACCESS_KEY in a .env file (free at web3forms.com) to send from this page. Otherwise we open your email app with the message prefilled.',
    cta3: '→ Start a Project',
    jobs: [
      { period: 'Sep 2025 — Present', role: 'Product Manager', co: 'Sehma B&B Holding · Home Health Care · Medellin',
        bullets: ['Designed and maintained <hl>data models + ETL processes</hl> to centralize operational information.','Built dashboards with KPIs focused on operations, conversion, and quality.','Automated reporting workflows through programming, <hl>reducing manual errors</hl> significantly.'] },
      { period: 'Oct 2024 — Mar 2025', role: 'Regional Support Professional', co: 'Hospital Alma Mater de Antioquia · Medellin',
        bullets: ['Managed <hl>geospatial data with ArcGIS</hl> to identify critical zones for public health interventions.','Produced periodic technical reports for regional epidemiological surveillance programs.','Consolidated multi-source data into reports directed at executive teams.'] },
      { period: 'Jan 2022 — Sep 2024', role: 'Health Information Analyst', co: 'Hospital Alma Mater de Antioquia · Medellin',
        bullets: ['Analyzed epidemiological and hospital data to support <hl>strategic institutional decision-making</hl>.','Designed automated Power BI reports achieving <hl>30% reduction in processing time</hl>.','Managed public health databases and regulatory reports submitted to the Ministry of Health.'] },
    ],
    projects: [
      { num: '01 / 2023', title: 'Antimicrobial Stewardship Program (PROA)', org: 'Hospital Alma Mater de Antioquia',
        desc: 'Custom web module for the infectology department integrating antibiotic dispensing control and bacterial resistance surveillance.', impact: '↓ 12% Reduction in Defined Daily Doses (DDD)' },
      { num: '02 / 2021', title: 'Infrastructure Warehouse Supply Control', org: 'Hospital Alma Mater de Antioquia',
        desc: 'Administrative module automating tracking of entries and exits, optimizing stock levels and reducing asset losses.', impact: '↓ 45% Reduction in Asset Losses' },
    ],
    footer1: '© 2025 Matteo Rodriguez Carmona', footer2: 'Data Analyst · Data Engineer · Full Stack Dev',
  },
  es: {
    navLinks: ['Pitch', 'Habilidades', 'Experiencia', 'Proyectos', 'Datos abiertos', 'Contacto'],
    heroTag: 'Analista de Datos · Data Engineer · Full Stack Developer',
    heroDesc: 'Transformo datos complejos en decisiones que generan impacto real. Especializado en analítica de salud, pipelines ETL y desarrollo full stack para entornos operativos y clínicos.',
    cta1: 'Contáctame', cta2: 'Ver Proyectos',
    statsLabels: ['Años de Experiencia', 'Tiempo Ahorrado', 'Reducción de Pérdidas', 'Reducción DDD', 'Idiomas'],
    pitchTag: '// 00 — Por qué contratarme', pitchTitle: 'El Pitch',
    pitchHeadline: 'Tienes datos.\nNecesitas decisiones.',
    pitchDesc: 'La mayoría de las empresas tienen datos sin procesar que nadie convierte en información útil. Yo cierro esa brecha — construyo pipelines que limpian y centralizan tus datos, dashboards que tu equipo realmente usa, y automatizaciones que eliminan el trabajo manual. Lo he hecho en hospitales y salud domiciliaria. Puedo hacerlo para ti.',
    pitchCards: [
      { icon: '⚙', title: 'Data Engineer', desc: 'Pipelines ETL, PostgreSQL, Power Automate. Tus datos, centralizados y limpios.' },
      { icon: '📊', title: 'Analista de Datos', desc: 'Power BI, Tableau, R, Python. Insights accionables para tus directivos.' },
      { icon: '🌐', title: 'Full Stack Dev', desc: 'React, TypeScript, SQL. Módulos a medida construidos para tu operación.' },
    ],
    s1tag: '// 01 — Capacidades', s1title: 'Stack Técnico',
    s2tag: '// 02 — Trayectoria', s2title: 'Experiencia',
    s3tag: '// 03 — Lo que he construido', s3title: 'Proyectos',
    vizTag: '// Live — Visualización',
    vizTitle: 'Top 10 productos por precio promedio',
    vizCaption:
      'Gráfico desde JSON público (pipeline canasta familiar · Datos Abiertos Colombia). Ejes: Producto vs precio_promedio en COP.',
    vizMetaLeft: 'Ordenado por precio_promedio · descendente',
    vizMetaRight: 'Recharts · ResponsiveContainer',
    s4tag: '// 04 — Contacto', s4title: 'Hablemos',
    avail: 'Disponible para proyectos freelance',
    contactDesc: '¿Necesitas un analista, ingeniero de datos o desarrollador que entienda el negocio? Construyamos algo que realmente marque la diferencia.',
    contactTabChannels: 'Directo',
    contactTabForm: 'Contact Form',
    formName: 'Nombre',
    formEmail: 'Correo',
    formMessage: 'Mensaje',
    formSubmit: 'Enviar mensaje',
    formSending: 'Enviando...',
    formSuccess: 'Gracias - te respondo pronto.',
    formError: 'No se pudo enviar. Intenta de nuevo o usa el enlace de correo.',
    formHintNoKey: 'Agrega VITE_WEB3FORMS_ACCESS_KEY en un archivo .env (gratis en web3forms.com) para enviar desde esta pagina. Si no, abrimos tu app de correo con el mensaje listo.',
    cta3: '→ Iniciar Proyecto',
    jobs: [
      { period: 'Sep 2025 — Presente', role: 'Product Manager', co: 'Sehma B&B Holding · Home Health Care · Medellín',
        bullets: ['Diseñé y mantengo <hl>modelos de datos y procesos ETL</hl> para centralizar información operativa.','Construí dashboards con KPIs de operaciones, conversión y calidad para mejorar la visibilidad del negocio.','Automaticé flujos de reportes — <hl>reduciendo errores manuales</hl> significativamente.'] },
      { period: 'Oct 2024 — Mar 2025', role: 'Profesional de Apoyo Regional', co: 'Hospital Alma Mater de Antioquia · Medellín',
        bullets: ['Gestioné <hl>datos geoespaciales con ArcGIS</hl> para identificar zonas críticas en salud pública.','Produje informes técnicos periódicos para programas de vigilancia epidemiológica regional.','Consolidé datos de múltiples fuentes en reportes para equipos directivos.'] },
      { period: 'Ene 2022 — Sep 2024', role: 'Analista de Información en Salud', co: 'Hospital Alma Mater de Antioquia · Medellín',
        bullets: ['Analicé datos epidemiológicos y hospitalarios para apoyar <hl>decisiones estratégicas institucionales</hl>.','Diseñé reportes automatizados en Power BI logrando <hl>30% de reducción en tiempo de procesamiento</hl>.','Gestioné bases de datos de salud pública y reportes regulatorios ante el Ministerio de Salud.'] },
    ],
    projects: [
      { num: '01 / 2023', title: 'Programa de Gestión Antibiótica (PROA)', org: 'Hospital Alma Mater de Antioquia',
        desc: 'Módulo web personalizado para infectología integrando control de dispensación de antibióticos y vigilancia de resistencia bacteriana.', impact: '↓ 12% Reducción en Dosis Diarias Definidas (DDD)' },
      { num: '02 / 2021', title: 'Control de Suministros en Infraestructura', org: 'Hospital Alma Mater de Antioquia',
        desc: 'Módulo administrativo que automatiza el seguimiento de entradas y salidas de bodega, optimizando niveles de stock y reduciendo pérdidas.', impact: '↓ 45% Reducción en Pérdida de Activos' },
    ],
    footer1: '© 2025 Matteo Rodriguez Carmona', footer2: 'Analista de Datos · Data Engineer · Full Stack Dev',
  },
}
